# Generated by Django 5.2 on 2025-05-05 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_meeting_details_booking_meeting_url'),
        ('vendor', '0003_rename_vendor_vendorprofile_staffmember_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='vendor.vendorprofile'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='weekday',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')]),
        ),
    ]
